[package]
name = "reginald"

version.workspace    = true
authors.workspace    = true
edition.workspace    = true
repository.workspace = true
license.workspace    = true


[features]
derive = ["dep:reginald_derive"]

[dependencies]
reginald_derive = { path = "../reginald_derive" , optional = true }
